In [25]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# 第一个版本
其中不参与 计算的特征 os,osv, lan, sid 不参与建模

In [3]:
# 数据加载
train_data = pd.read_csv("./track_challenge/train.csv")
test_1_data =pd.read_csv("./track_challenge/test1.csv")

In [5]:
train_data.head(2)

,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,label,lan,media_id,ntt,os,osv,package,sid,timestamp,version,fea_hash,location,fea1_hash,cus_type
0,316361,1199,46000,0,0,0,1,NaN,104,6,android,9,18,1438873,1.560000e+12,8,2135019403,0,2329670524,601
1,135939,893,0,0,0,0,1,NaN,19,6,android,8.1,0,1185582,1.560000e+12,4,2782306428,1,2864801071,1000

In [28]:
test_1_data = test_1_data.iloc[:,1:]
test_1_data

,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,lan,media_id,ntt,os,osv,package,sid,timestamp,version,fea_hash,location,fea1_hash,cus_type
0,317625,1181,46000.0,2196.0,2.0,1080.0,CN,639,2.0,Android,8.1.0,188,1440682,1.559872e+12,7,1672223856,57,3872258917,658
1,435108,944,46003.0,2280.0,3.0,1080.0,zh-CN,704,6.0,Android,8.1.0,221,1606824,1.559739e+12,3,3767901757,23,129322164,943
2,0,1106,46000.0,0.0,0.0,0.0,NaN,39,2.0,android,5.1,1562,1774642,1.559614e+12,0,454638703,30,4226678391,411
3,451504,761,46000.0,1344.0,0.0,720.0,NaN,54,2.0,android,7.1.1,9,1742535,1.559668e+12,0,1507622951,65,3355419572,848
4,0,1001,46000.0,665.0,0.0,320.0,zh-CN,29,5.0,Android,8.1.0,4,1689686,1.559694e+12,0,4116351093,148,2644467751,411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,0,1001,46000.0,760.0,0.0,360.0,zh-CN,29,2.0,Android,8.1.0,4,1165373,1.559957e+12,0,3162887451,126,2711576615,411
149996,0,1001,46000.0,780.0,0.0,360.0,zh-CN,29,2.0,Android,9.0.0,4,1444115,1.559863e+12,0,97238959,322,2678022183,411
149997,0,1001,46000.0,780.0,0.0,360.0,zh-CN,29,5.0,Android,8.1.0,4,1134378,1.560041e+12,0,1320118495,46,2610913319,411
149998,500925,1052,46000.0,854.0,240.0,480.0,zh-CN,249,6.0,android,4.4.2,0,1700238,1.559688e+12,2,1292986591,41,1898209327,430
149999,0,1001,46000.0,780.0,0.0,360.0,zh-CN,29,2.0,Android,9.0.0,4,1201539,1.559950e+12,0,259614175,122,2594136103,411

In [32]:
test_1_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 19 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   android_id  150000 non-null  int64
 1   apptype     150000 non-null  int64
 2   carrier     150000 non-null  float64
 3   dev_height  150000 non-null  float64
 4   dev_ppi     150000 non-null  float64
 5   dev_width   150000 non-null  float64
 6   lan         94453 non-null   object
 7   media_id    150000 non-null  int64
 8   ntt         150000 non-null  float64
 9   os          150000 non-null  object
 10  osv         148008 non-null  object
 11  package     150000 non-null  int64
 12  sid         150000 non-null  int64
 13  timestamp   150000 non-null  float64
 14  version     150000 non-null  object
 15  fea_hash    150000 non-null  object
 16  location    150000 non-null  int64
 17  fea1_hash   150000 non-null  int64
 18  cus_type    150000 non-null  int64
dtypes: float64(6), int64(8), object(5)
memory usage: 21.7+ MB

In [11]:
train_data.info()
# object类型： lan, os,osv, version, fea_hash
object_cols = train_data.select_dtypes(include='object').columns

# 缺失值个数
tmp = train_data.isnull().sum()
tmp[tmp>0]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 20 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   android_id  500000 non-null  int64
 1   apptype     500000 non-null  int64
 2   carrier     500000 non-null  int64
 3   dev_height  500000 non-null  int64
 4   dev_ppi     500000 non-null  int64
 5   dev_width   500000 non-null  int64
 6   label       500000 non-null  int64
 7   lan         316720 non-null  object
 8   media_id    500000 non-null  int64
 9   ntt         500000 non-null  int64
 10  os          500000 non-null  object
 11  osv         493439 non-null  object
 12  package     500000 non-null  int64
 13  sid         500000 non-null  int64
 14  timestamp   500000 non-null  float64
 15  version     500000 non-null  object
 16  fea_hash    500000 non-null  object
 17  location    500000 non-null  int64
 18  fea1_hash   500000 non-null  int64
 19  cus_type    500000 non-null  int64
dtypes: float64(1), int64(14), object(5)
memory usage: 76.3+ MB

lan    183280
osv      6561
dtype: int64

## 缺失值 lan osv
## object类型： lan, os,osv, version, fea_hash

In [16]:
features = train_data.columns.tolist()
features.remove('label') # 去除label

# 特征的唯一值查看
for feature in features:
    print(feature, train_data[feature].nunique())

android_id 362258
apptype 89
carrier 5
dev_height 798
dev_ppi 92
dev_width 346
lan 21
media_id 284
ntt 8
os 2
osv 148
package 1950
sid 500000
timestamp 1
version 17
fea_hash 402980
location 332
fea1_hash 4959
cus_type 58

In [20]:
# thinking fea_hash需要做特征变换吗？
train_data['fea_hash'].value_counts()

68083895      110
235856055      99
51306679       91
2815114810     77
16777343       60
             ...
3826231931      1
3154737014      1
1949572865      1
2718364127      1
1697301943      1
Name: fea_hash, Length: 402980, dtype: int64

In [21]:
train_data['fea_hash'].describe() 
# 我们看到最多的hash值 唯一值有多少
# 可以把hash值转为str,求长度，根据长度做一个类型映射

count       500000
unique      402980
top       68083895
freq           110
Name: fea_hash, dtype: object

In [22]:
train_data['fea_hash'].map(lambda x: len(str(x))).value_counts()

10    378925
9     108904
8      11235
7        740
6         93
38        37
39        28
37        16
5         11
36         3
33         2
32         2
1          2
30         1
31         1
Name: fea_hash, dtype: int64

In [23]:
remove_list = ['os','osv','lan', 'sid']
col = features
for c in remove_list:
    col.remove(c)
col

['android_id',
 'apptype',
 'carrier',
 'dev_height',
 'dev_ppi',
 'dev_width',
 'media_id',
 'ntt',
 'package',
 'timestamp',
 'version',
 'fea_hash',
 'location',
 'fea1_hash',
 'cus_type']

In [40]:
# 特征筛选
selected_feature = train_data[col]
# 构造一个新的特征 fea_hash_len
selected_feature['fea_hash_len'] = selected_feature['fea_hash'].map(lambda x: len(str(x)))
selected_feature['fea1_hash_len'] = selected_feature['fea1_hash'].map(lambda x: len(str(x)))
# Thinking 为什么要把很大的数字处理为0 异常值处理，长尾分布 
# 如果fea_hash很长的话，都归为0
selected_feature['fea_hash'] = selected_feature['fea_hash'].map(lambda x: 0 if len(str(x))> 16 else int(x))
selected_feature['fea1_hash'] = selected_feature['fea1_hash'].map(lambda x: 0 if len(str(x))> 16 else int(x))

selected_feature

,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,media_id,ntt,package,timestamp,version,fea_hash,location,fea1_hash,cus_type,fea_hash_len,fea1_hash_len
0,316361,1199,46000,0,0,0,104,6,18,1.560000e+12,8,2135019403,0,2329670524,601,10,10
1,135939,893,0,0,0,0,19,6,0,1.560000e+12,4,2782306428,1,2864801071,1000,10,10
2,399254,821,0,760,0,360,559,0,0,1.560000e+12,0,1392806005,2,628911675,696,10,9
3,68983,1004,46000,2214,0,1080,129,2,0,1.560000e+12,0,3562553457,3,1283809327,753,10,10
4,288999,1076,46000,2280,0,1080,64,2,0,1.560000e+12,5,2364522023,4,1510695983,582,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,392477,1028,46000,1920,3,1080,144,6,25,1.560000e+12,7,861755946,79,140647032,373,9,9
499996,346134,1001,0,1424,0,720,29,2,0,1.560000e+12,3,1714444511,23,2745131047,525,10,10
499997,499635,761,46000,1280,0,720,54,6,9,1.560000e+12,0,3843262581,25,1326115882,810,10,10
499998,239786,917,46001,960,0,540,109,2,0,1.560000e+12,0,1984296118,225,1446741112,772,10,10
499999,270531,929,46000,2040,3,1080,59,2,78,1.560000e+12,5,1697301943,49,1915763579,1076,10,10

In [39]:
# test 特征筛选
test_selected_feature = test_1_data[col]
# 构造一个新的特征 fea_hash_len
test_selected_feature['fea_hash_len'] = test_selected_feature['fea_hash'].map(lambda x: len(str(x)))
test_selected_feature['fea1_hash_len'] = test_selected_feature['fea1_hash'].map(lambda x: len(str(x)))
# Thinking 为什么要把很大的数字处理为0 异常值处理，长尾分布 
# 如果fea_hash很长的话，都归为0
test_selected_feature['fea_hash'] = test_selected_feature['fea_hash'].map(lambda x: 0 if len(str(x))> 16 else int(x))
test_selected_feature['fea1_hash'] = selected_feature['fea1_hash'].map(lambda x: 0 if len(str(x))> 16 else int(x))

test_selected_feature.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 17 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   android_id     150000 non-null  int64
 1   apptype        150000 non-null  int64
 2   carrier        150000 non-null  float64
 3   dev_height     150000 non-null  float64
 4   dev_ppi        150000 non-null  float64
 5   dev_width      150000 non-null  float64
 6   media_id       150000 non-null  int64
 7   ntt            150000 non-null  float64
 8   package        150000 non-null  int64
 9   timestamp      150000 non-null  float64
 10  version        150000 non-null  object
 11  fea_hash       150000 non-null  int64
 12  location       150000 non-null  int64
 13  fea1_hash      150000 non-null  int64
 14  cus_type       150000 non-null  int64
 15  fea_hash_len   150000 non-null  int64
 16  fea1_hash_len  150000 non-null  int64
dtypes: float64(6), int64(10), object(1)
memory usage: 19.5+ MB

In [41]:
# 使用lgb 训练模型
import lightgbm as lgb

model = lgb.LGBMClassifier()
# 训练模型
model.fit(selected_feature.drop(['timestamp','version'],axis=1), train_data['label'])

# 模型预测
result = model.predict(test_selected_feature.drop(['timestamp','version'],axis=1))
result

array([0, 0, 0, ..., 1, 1, 1])

In [44]:
# submit 文件
res = pd.DataFrame(test_1_data['sid'])
res['label'] = result
res.to_csv("./track_baseline.csv", index=False)

In [46]:
## 现在思考怎么在提升呢？
# osv特征灭有利用
# timestamp特征没有利用 提取时间的多个维度 年月日 周
# 时间的滑动窗口 取diff的最小值
# train_timestamp =pd.to_datetime(selected_feature['timestamp'])
# train_timestamp
selected_feature['timestamp'].value_counts()

1.560000e+12    500000
Name: timestamp, dtype: int64

In [ ]:
# 树模型不需要做归一化，因为基于节点做分裂，只要不改变数据的顺序。
# lgb xgboost 一般都是不需要做，但是需要对于类别特征做映射 laberencoder 需要保持原始顺序不变